openapi: 3.0.0
info:
  version: 1.0.0
  title: Simple API
  description: A simple API to illustrate OpenAPI concepts
servers:
  - url: "{apiRoot}/simple-apis/v1"
    variables:
      apiRoot:
        default: https://example.com
        description: apiRoot as defined in subclause 7.5 of 3GPP TS 29.222.
paths:
  /ping:
    get:
      description: Returns "pong" if service is avaliable
      responses:
        "200":
          description: Successful response
  /test:
    get:
      description: Test
      responses:
        "200":
          description: Successful response
